# This is the config file for the reconstruction.py file

modelPath: ../training/trained_data/DAE_DTI/          # directory of the saved model checkpoint
data_directory: ../../../data/Paper_request_data/HR               # directory to the raw data
save_directory: ../../../data/Paper_request_data/HR                   # directory where the directories of the reconstructions are created and the results then stored

coil_file_name: coils_reord          # name of the file storing coil sensitivities
data_file_name: kdat_slice_    # shared name of the data files
diff_enc_file_name: 1.0mm_126-dir_R3x3_dvs        # name of the dvs file storing b-values and gradient vectors of the acquisition

device: cuda                                      # device on which the reconstructions are run
reg_weight: 1e-2                                 # weighting of the TV regularization for LASER                         
slice_index: 0                                 # slice to reconstruction (beginning)
slice_increment: 1                                # up to which slice reconstruction shall be run?
fix_PF: false                                    # fix partial fourier artifacts in reconstructed images
PF_factor: 1                                   # number of partial fourier lines to fix

muse_recon: True                                 # running Muse reconstruction
shot_recon: True                                 # running shot reconsturction of the multi shot acquisition (needs to be run before first time LASER)
LASER: True                                       # running LAtent Space dEcoded Reconstruction (LASER)
vae_reg_recon: False                              # running VAE-regularized reconstruction
vae_denoise_recon: false                          # running VAE denoising